apiVersion: v1
kind: Secret
metadata:
  name: cosmosdb-secret
type: Opaque
data:
  connection: bW9uZ29kYjovL2NoZWZjb25mOjBlQWJlbnp6QUsxTjlDbVJtazl6MFdDbWpJNGpPWDNlZWlZWTJxN0JtWVlwVjNuU0o1WFNoeXpvTUVQdUY2Y0hZVDQzam1RZjNWaW1GYlBuUzJhR0RRPT1AY2hlZmNvbmYuZG9jdW1lbnRzLmF6dXJlLmNvbToxMDI1NS9oZXJvcmF0aW5ncz9zc2w9dHJ1ZQ==
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: api
customVersion: v1beta2
spec:
  v1beta2:
    image: chefconf.azurecr.io/app/api:latest
    count: 1
    service:
      name: api-lb
      topology: standalone
    env:
      - name: MONGODB_URI
        valueFrom:
          secretKeyRef:
            name: cosmosdb-secret
            key: connection
      - name: NODE_ENV
        value: "development"
      - name: PORT
        value: 3000
    ports:
      - containerPort:  3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-lb
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 3000
    targetPort: 3000
  selector:
    habitat-name: api-lb